ARTIFACTS_DIR: "artifacts"
MODEL:
  BLOCKS:
    conv1: [3, 16, 3, 1, 0]
    res_blocks:
      [
        [16, 32, 3, 2, 1],
        [32, 64, 3, 2, 1],
        [64, 128, 3, 2, 1],
        [128, 256, 3, 2, 1],
        [256, 512, 3, 2, 1],
        [512, 512, 3, 2, 1],
      ]
    decoder:
      [
        [512, 256, 3, 2, 1, 1],
        [256, 128, 3, 2, 1, 1],
        [128, 64, 3, 2, 1, 1],
        [64, 32, 3, 2, 1, 1],
        [32, 16, 3, 2, 1, 1],
        [16, 3, 3, 2, 1, 1],
      ]
DATA:
  root_dir: "data/300W_LP"
  sub_dataset: "AFW"
  BFM: "BFM"
  img_size: [512, 512]
  batch_size: 8
OPTIM:
  loss: ""
  optimizer: "Adam"
  lr: 0.001
  accumulate_gradient: False
  accumulate_gradient_iters: 8
  num_epochs: 100
  num_iterations_val: 50
  save_ckpt_every: 10
  eval_every: 5
  gradient_clip: true
  scheduler: ""
  T_max: 100
  eta_min: 0.000001
