ARTIFACTS_DIR: "artifacts"
MODEL:
DATA:
  root_dir: "data/300W_LP"
  sub_dataset: "AFW"
  BFM: "BFM"
  img_size: [450, 450]
  batch_size: 8
  n_classes: 20
OPTIM:
  loss: ""
  optimizer: "SGD"
  lr: 0.001
  accumulate_gradient: False
  accumulate_gradient_iters: 8
  num_epochs: 100
  num_iterations_val: 50
  save_ckpt_every: 10
  eval_every: 5
  gradient_clip: true
  scheduler: ""
  T_max: 100
  eta_min: 0.000001
